name: ci

permissions:
  contents: write

on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo check
        run: cargo check

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo build
        run: |
          export BUILD_VERSION=$(git rev-parse --short HEAD)
          cargo build --release

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   # if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       target/release/mcp-proxy

      - name: Crates Release
        uses: katyo/publish-crates@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
